### ISSUE TITLE
Disable ssl for local test

### ISSUE THREAD

**Issue by Ja7ad** [leodip/goiabada#1]
Hello

How to disable ssl for local test via docker compose? I remove ssl environment but service stopped!!!

```yaml

      # The directory where the cert and key files are located (for HTTPS)
      - GOIABADA_CERTFILE=./cert/self_signed_cert.pem
      - GOIABADA_KEYFILE=./cert/self_signed_key.pem
```

```shell
goiabada-1      | 2023-12-15 19:08:51.034 INF base url: https://localhost:8100
goiabada-1      | 2023-12-15 19:08:51.034 INF open : no such file or directory
```

**Comment by leodip** [comment]
Hey. Currently, it's not possible, because in the code it will only listen with TLS:

https://github.com/leodip/goiabada/blob/main/authserver/src/internal/server/server.go#L67

Have you had issues with using a self signed certificate?

Based on your feedback, I will add a configuration option to make it run with http too, for testing/development.

**Comment by Ja7ad** [comment]
> Hey. Currently, it's not possible, because in the code it will only listen with TLS:
> 
> https://github.com/leodip/goiabada/blob/main/authserver/src/internal/server/server.go#L67
> 
> Have you had issues with using a self signed certificate?

For test or develop, need without SSL for debugging.

**Comment by leodip** [comment]
@Ja7ad  Thanks for giving this feedback, I have added support for http (non-TLS), if you want to have another look.
(it shouldn't be used in production though)

**Comment by Ja7ad** [comment]
Ok thanks
